language: python
python:
    - '2.6'
    - '2.7'
env:
    global:
        - secure: BaT6ULY2Rd4FfC2anf96wBS1AbDZlDc9EcfMpX74/1Vxg1OHCXkyI5TYUaa6HAiE0h4EIZ8dDtz+HmiCuYqHquEDcg7PTS5IeiDheQen95s7lWI4SplQF8CtC03+DH0ycEZbuyF5HYEmmAFg2H071rQPs9jxmFyTyeW6NxiifkA=
        - secure: hsMHLsw/azfPwb6j7TOrJvUubJZCANiDp4NIEvC4wEQojLhIiWfG7zfVjDS8ENLy7Ys4/PYwWuiADxxWJRLU+PnIRDT6+0LctSSV2wf8cBuqtghOIZyP0SNWbZNYBU9Q1yLbtlgN7X+hhgu4LhnRYDMeWUFfPgHLyhtYSvcB0Vg=
before_script:
    - if [ "$TRAVIS_PULL_REQUEST" == false ] && [ "$SAUCE_USERNAME" ] && [ "$SAUCE_ACCESS_KEY" ]; then SAUCE_OK=1; else SAUCE_OK=0; fi 
    - function START_SAUCE_CONNECT { curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash & }
    - if [ "$SAUCE_OK" == 1 ]; then START_SAUCE_CONNECT; fi;
install:
    - pip install zc.buildout distribute selenium
    - buildout
    - echo "yes" | sudo add-apt-repository ppa:chris-lea/node.js
    - sudo apt-get update
    - sudo apt-get install nodejs phantomjs
    - sudo npm install -g grunt-cli grunt-init bower
    - sudo npm install
    - bower install
    - cp example-config.json config.json
script:
    - ./require.sh
    - ./bin/test
    - ./dummy_api/start.sh
    - echo 'API_BASE = "http://localhost:8282/"' >> regulations/settings/local_settings.py
    - ./run_server.sh &
    - sleep 5
    - if [ "$SAUCE_OK" == 1 ]; then nosetests regulations/uitests/*.py; fi
    - grunt test
