language: python
python:
    - '2.6'
    - '2.7'
env:
    global:
        - secure: QsUegKVhNm7TOUNxFwirgFmk1nzALT+VyRw3FGRbbCUESl812ZmQMQutnVWNfbgVDO6vDayZbWlCxcIDYTcss+qTb7we6OwxyKg8vqslvnO58cQ2m9QtUQwCW4tIQdHCJ0k604B3C/EXaa6nVvlamVLNoh0DLjVPYZJvEBxT5Uw=
        - secure: f8d95SWXm59L+EBjr6DJHL5Xd7qDl86Bc3fHz+ULSLG24p2siGOmqA9TDzNqUN5KiTg0z7xdQ0eKq4I9qxZG+oCWTh+KZkMpHawJN8yMeNJxFicZnFk2T0OgVjjUpPhNl+zBnguWz6c71FBavpm81rzaUhDjW6XenAfGbJZep+o=
before_script:
    - if [ "$TRAVIS_PULL_REQUEST" == false ] && [ "$SAUCE_USERNAME" ] && [ "$SAUCE_ACCESS_KEY" ]; then SAUCE_OK=1; else SAUCE_OK=0; fi 
    - function START_SAUCE_CONNECT { curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash & }
    - if [ "$SAUCE_OK" == 1 ]; then START_SAUCE_CONNECT; fi;
install:
    - pip install zc.buildout distribute selenium
    - buildout
    - echo "yes" | sudo add-apt-repository ppa:chris-lea/node.js
    - sudo apt-get update
    - sudo apt-get install nodejs phantomjs
    - sudo npm install -g grunt-cli grunt-init bower
    - sudo npm install
    - bower install
    - cp example-config.json config.json
script:
    - ./require.sh
    - ./bin/test
    - ./dummy_api/start.sh
    - echo 'API_BASE = "http://localhost:8282/"' >> regulations/settings/local_settings.py
    - ./run_server.sh &
    - sleep 5
    - if [ "$SAUCE_OK" == 1 ]; then nosetests regulations/uitests/*.py; fi
    - grunt test
