language: python
python:
    - '2.6'
    - '2.7'
addons:
    sauce_connect: 
        username: "cfpberegs"
        access_key:
            secure: "DpQCYnrJl72ZnRO1ko3ufPq3HKOlT1Q+G+6OEF3t6IhWBnnzWXYgcoxOqV1/lxnHo6ymh9pNv2hzeVw/W3JMQ23wg3rA6UnfVJ93JglXO8SNWaYIlxqDEHIg4B3S4RJXJ5M2iCZnVn6xF3zHgER0+6VtOVJXXPSQqiiqJD2v33Q="
install:
    - pip install zc.buildout distribute selenium
    - buildout
    - echo "yes" | sudo add-apt-repository ppa:chris-lea/node.js
    - sudo apt-get update
    - sudo apt-get install nodejs phantomjs
    - sudo npm install -g grunt-cli grunt-init bower
    - sudo npm install
    - bower install
    - cp example-config.json config.json
script:
    - ./require.sh
    - ./bin/test
    - ./dummy_api/start.sh
    - echo 'API_BASE = "http://localhost:8282/"' >> regulations/settings/local_settings.py
    - ./run_server.sh &
    - sleep 6
    - if [ "$SAUCE_USERNAME" ] && [ "$SAUCE_ACCESS_KEY" ]; then nosetests regulations/uitests/*.py; fi
    - grunt test
