language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install zc.buildout distribute
    - buildout
    - echo "yes" | sudo add-apt-repository ppa:chris-lea/node.js
    - sudo apt-get update
    - sudo apt-get install nodejs phantomjs
    - sudo npm install -g grunt-cli grunt-init
    - sudo npm install
    - cp example-config.json config.json
script:
    - ./require.sh
    - ./bin/test
    - ./dummy_api/start.sh
    - echo 'API_BASE = "http://localhost:8282/"' >> regserver/settings/local_settings.py
    - grunt test
